modmap:
  - name: caps remap
    remap: 
      CapsLock:
        held: super_l
        alone: esc
        alone_timeout_millis: 150
  - name: esc to caps
    remap:
      Esc:
        held: CapsLock
        alone: esc
        alone_timeout_millis: 400

